/*// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart';
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXTWBB75qVGH9ODPIEm1XpCp0fJVxgo7c',
    appId: '1:454700021765:web:826bda3c7a8f37f0c7046c',
    messagingSenderId: '454700021765',
    projectId: 'weconnect-da33f',
    authDomain: 'weconnect-da33f.firebaseapp.com',
    storageBucket: 'weconnect-da33f.firebasestorage.app',
    measurementId: 'G-BQQMB14SKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8IoDEW941_VR4Zx38D78qyVh3eW9VFQ',
    appId: '1:454700021765:android:9abcbdd675ec436fc7046c',
    messagingSenderId: '454700021765',
    projectId: 'weconnect-da33f',
    storageBucket: 'weconnect-da33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgXsCBky_l0qt5UHBalb_ylf19_pHWzmQ',
    appId: '1:454700021765:ios:ea72dbfcacecac03c7046c',
    messagingSenderId: '454700021765',
    projectId: 'weconnect-da33f',
    storageBucket: 'weconnect-da33f.firebasestorage.app',
    iosBundleId: 'com.example.weconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgXsCBky_l0qt5UHBalb_ylf19_pHWzmQ',
    appId: '1:454700021765:ios:ea72dbfcacecac03c7046c',
    messagingSenderId: '454700021765',
    projectId: 'weconnect-da33f',
    storageBucket: 'weconnect-da33f.firebasestorage.app',
    iosBundleId: 'com.example.weconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXTWBB75qVGH9ODPIEm1XpCp0fJVxgo7c',
    appId: '1:454700021765:web:d73b7c18fec97759c7046c',
    messagingSenderId: '454700021765',
    projectId: 'weconnect-da33f',
    authDomain: 'weconnect-da33f.firebaseapp.com',
    storageBucket: 'weconnect-da33f.firebasestorage.app',
    measurementId: 'G-6SXB4S6LM5',
  );

}

*/